name: JSCPP Compiler Tests

on:
  push:
    branches: [ master, experiment-development ]
  pull_request:
    branches: [ master, experiment-development ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel cmake gcc make

      - name: Configure & Build
        run: |
          mkdir -p build
          cd build
          cmake ..
          make -j$(nproc)

      - name: Run main.jscpp
        run: |
          cd build
          ./ujscc ../src/main.jscpp || exit 1

      - name: Test error handling
        run: |
          cd build
          # create intentionally broken file
          cat > test_error.jscpp <<'EOF'
          Uoc main() {
            print("Unclosed);
          }
          EOF

          if ./ujscc test_error.jscpp; then
            echo "Error test FAILED (compiler did not exit with error)"
            exit 1
          else
            echo "Error test PASSED"
          fi
